// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SnakeClassic.Infrastructure.Persistence;

#nullable disable

namespace SnakeClassic.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251225040932_AddDailyChallenges")]
    partial class AddDailyChallenges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SnakeClassic.Domain.Entities.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AchievementId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("achievement_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<int>("CoinReward")
                        .HasColumnType("integer")
                        .HasColumnName("coin_reward");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean")
                        .HasColumnName("is_secret");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("RequirementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("requirement_type");

                    b.Property<int>("RequirementValue")
                        .HasColumnType("integer")
                        .HasColumnName("requirement_value");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tier");

                    b.Property<int>("XpReward")
                        .HasColumnType("integer")
                        .HasColumnName("xp_reward");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId")
                        .IsUnique()
                        .HasDatabaseName("i_x_achievements_achievement_id");

                    b.HasIndex("Category")
                        .HasDatabaseName("i_x_achievements_category");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_achievements_is_active");

                    b.ToTable("achievements");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.BattlePassSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Dictionary<string, object>>("ExtraData")
                        .HasColumnType("jsonb")
                        .HasColumnName("extra_data");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<List<Dictionary<string, object>>>("LevelsConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("levels_config");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("integer")
                        .HasColumnName("max_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("SeasonId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("season_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("theme");

                    b.Property<string>("ThemeColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("theme_color");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_battle_pass_seasons_is_active");

                    b.HasIndex("SeasonId")
                        .IsUnique()
                        .HasDatabaseName("i_x_battle_pass_seasons_season_id");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("i_x_battle_pass_seasons_start_date_end_date");

                    b.ToTable("battle_pass_seasons");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.DailyChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("ChallengeDate")
                        .HasColumnType("date")
                        .HasColumnName("challenge_date");

                    b.Property<int>("CoinReward")
                        .HasColumnType("integer")
                        .HasColumnName("coin_reward");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<string>("RequiredGameMode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("required_game_mode");

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer")
                        .HasColumnName("target_value");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<int>("XpReward")
                        .HasColumnType("integer")
                        .HasColumnName("xp_reward");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeDate")
                        .HasDatabaseName("i_x_daily_challenges_challenge_date");

                    b.HasIndex("ChallengeDate", "Difficulty")
                        .HasDatabaseName("i_x_daily_challenges_challenge_date_difficulty");

                    b.ToTable("daily_challenges");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.DailyLoginBonus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_streak");

                    b.Property<DateOnly?>("LastClaimDate")
                        .HasColumnType("date")
                        .HasColumnName("last_claim_date");

                    b.Property<int>("TotalClaims")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_claims");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_daily_login_bonuses_user_id");

                    b.ToTable("daily_login_bonuses");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.FcmToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("platform");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.PrimitiveCollection<string>("SubscribedTopics")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("subscribed_topics");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("i_x_fcm_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_fcm_tokens_user_id");

                    b.ToTable("fcm_tokens");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FriendId")
                        .HasColumnType("uuid")
                        .HasColumnName("friend_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FriendId", "Status")
                        .HasDatabaseName("i_x_friendships_friend_id_status");

                    b.HasIndex("UserId", "FriendId")
                        .IsUnique()
                        .HasDatabaseName("i_x_friendships_user_id_friend_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("i_x_friendships_user_id_status");

                    b.ToTable("friendships");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.GameReplay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<int>("FinalScore")
                        .HasColumnType("integer")
                        .HasColumnName("final_score");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<Dictionary<string, object>>("ReplayData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("replay_data");

                    b.Property<Guid?>("ScoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("score_id");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("i_x_game_replays_created_at");

                    b.HasIndex("IsPublic")
                        .HasDatabaseName("i_x_game_replays_is_public");

                    b.HasIndex("ScoreId")
                        .IsUnique()
                        .HasDatabaseName("i_x_game_replays_score_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_game_replays_user_id");

                    b.ToTable("game_replays");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.MatchmakingQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConnectionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("connection_id");

                    b.Property<int>("DesiredPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("desired_players");

                    b.Property<bool>("IsMatched")
                        .HasColumnType("boolean")
                        .HasColumnName("is_matched");

                    b.Property<Guid?>("MatchedGameId")
                        .HasColumnType("uuid")
                        .HasColumnName("matched_game_id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mode");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_matchmaking_queues_user_id")
                        .HasFilter("is_matched = false");

                    b.HasIndex("Mode", "DesiredPlayers", "IsMatched", "QueuedAt")
                        .HasDatabaseName("i_x_matchmaking_queues_mode_desired_players_is_matched_queued_at");

                    b.ToTable("matchmaking_queues");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.MultiplayerGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<List<Dictionary<string, object>>>("FoodPositions")
                        .HasColumnType("jsonb")
                        .HasColumnName("food_positions");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("game_id");

                    b.Property<Dictionary<string, object>>("GameSettings")
                        .HasColumnType("jsonb")
                        .HasColumnName("game_settings");

                    b.Property<Guid?>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("max_players");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mode");

                    b.Property<List<Dictionary<string, object>>>("PowerUps")
                        .HasColumnType("jsonb")
                        .HasColumnName("power_ups");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("room_code");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("i_x_multiplayer_games_created_at");

                    b.HasIndex("GameId")
                        .IsUnique()
                        .HasDatabaseName("i_x_multiplayer_games_game_id");

                    b.HasIndex("RoomCode")
                        .HasDatabaseName("i_x_multiplayer_games_room_code");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_multiplayer_games_status");

                    b.ToTable("multiplayer_games");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.MultiplayerPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConnectionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("connection_id");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<DateTime?>("DisconnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disconnected_at");

                    b.Property<DateTime?>("EliminatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eliminated_at");

                    b.Property<int?>("EliminationRank")
                        .HasColumnType("integer")
                        .HasColumnName("elimination_rank");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_alive");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ready");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTime>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_at");

                    b.Property<int>("PlayerIndex")
                        .HasColumnType("integer")
                        .HasColumnName("player_index");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("SnakeColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("snake_color");

                    b.Property<List<Dictionary<string, object>>>("SnakePositions")
                        .HasColumnType("jsonb")
                        .HasColumnName("snake_positions");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .HasDatabaseName("i_x_multiplayer_players_game_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_multiplayer_players_user_id");

                    b.HasIndex("GameId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_multiplayer_players_game_id_user_id");

                    b.ToTable("multiplayer_players");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.NotificationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Dictionary<string, object>>("ExtraData")
                        .HasColumnType("jsonb")
                        .HasColumnName("extra_data");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer")
                        .HasColumnName("failure_count");

                    b.Property<string>("NotificationId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("notification_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("priority");

                    b.Property<string>("RecipientType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("recipient_type");

                    b.Property<int>("RecipientsCount")
                        .HasColumnType("integer")
                        .HasColumnName("recipients_count");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("integer")
                        .HasColumnName("success_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("SentAt")
                        .IsDescending()
                        .HasDatabaseName("i_x_notification_histories_sent_at");

                    b.HasIndex("Type")
                        .HasDatabaseName("i_x_notification_histories_type");

                    b.ToTable("notification_histories");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutoRenewing")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_renewing");

                    b.PrimitiveCollection<string>("ContentUnlocked")
                        .HasColumnType("jsonb")
                        .HasColumnName("content_unlocked");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsSubscription")
                        .HasColumnType("boolean")
                        .HasColumnName("is_subscription");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("platform");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("PurchaseTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_timestamp");

                    b.Property<string>("ReceiptData")
                        .HasColumnType("text")
                        .HasColumnName("receipt_data");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("transaction_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VerificationError")
                        .HasColumnType("text")
                        .HasColumnName("verification_error");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("i_x_purchases_created_at");

                    b.HasIndex("IsVerified")
                        .HasDatabaseName("i_x_purchases_is_verified");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("i_x_purchases_product_id");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasDatabaseName("i_x_purchases_transaction_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_purchases_user_id");

                    b.ToTable("purchases");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.ScheduledJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_id");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("job_name");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_type");

                    b.Property<DateTime?>("NextRunTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_time");

                    b.Property<Dictionary<string, object>>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Dictionary<string, object>>("TriggerConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("trigger_config");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trigger_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasDatabaseName("i_x_scheduled_jobs_job_id");

                    b.HasIndex("NextRunTime")
                        .HasDatabaseName("i_x_scheduled_jobs_next_run_time");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_scheduled_jobs_status");

                    b.ToTable("scheduled_jobs");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.Score", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("difficulty");

                    b.Property<int>("FoodsEaten")
                        .HasColumnType("integer")
                        .HasColumnName("foods_eaten");

                    b.Property<Dictionary<string, object>>("GameData")
                        .HasColumnType("jsonb")
                        .HasColumnName("game_data");

                    b.Property<int>("GameDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("game_duration_seconds");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("game_mode");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTime?>("PlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at");

                    b.Property<int>("ScoreValue")
                        .HasColumnType("integer")
                        .HasColumnName("score_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_scores_created_at");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("i_x_scores_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("ScoreValue")
                        .IsDescending()
                        .HasDatabaseName("i_x_scores_score_value");

                    b.HasIndex("GameMode", "Difficulty")
                        .HasDatabaseName("i_x_scores_game_mode_difficulty");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("i_x_scores_user_id_created_at");

                    b.ToTable("scores");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("EntryFee")
                        .HasColumnType("integer")
                        .HasColumnName("entry_fee");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("integer")
                        .HasColumnName("max_participants");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("max_players");

                    b.Property<int>("MinLevel")
                        .HasColumnType("integer")
                        .HasColumnName("min_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Dictionary<string, object>>("PrizeDistribution")
                        .HasColumnType("jsonb")
                        .HasColumnName("prize_distribution");

                    b.Property<int>("PrizePool")
                        .HasColumnType("integer")
                        .HasColumnName("prize_pool");

                    b.Property<Dictionary<string, object>>("Rules")
                        .HasColumnType("jsonb")
                        .HasColumnName("rules");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TournamentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tournament_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("i_x_tournaments_end_date");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("i_x_tournaments_start_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_tournaments_status");

                    b.HasIndex("TournamentId")
                        .IsUnique()
                        .HasDatabaseName("i_x_tournaments_tournament_id");

                    b.HasIndex("Status", "StartDate")
                        .HasDatabaseName("i_x_tournaments_status_start_date");

                    b.ToTable("tournaments");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.TournamentEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BestScore")
                        .HasColumnType("integer")
                        .HasColumnName("best_score");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("games_played");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_played_at");

                    b.Property<Dictionary<string, object>>("PrizeAmount")
                        .HasColumnType("jsonb")
                        .HasColumnName("prize_amount");

                    b.Property<bool>("PrizeClaimed")
                        .HasColumnType("boolean")
                        .HasColumnName("prize_claimed");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_tournament_entries_user_id");

                    b.HasIndex("TournamentId", "BestScore")
                        .IsDescending(false, true)
                        .HasDatabaseName("i_x_tournament_entries_tournament_id_best_score");

                    b.HasIndex("TournamentId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_tournament_entries_tournament_id_user_id");

                    b.ToTable("tournament_entries");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("auth_provider");

                    b.Property<int>("Coins")
                        .HasColumnType("integer")
                        .HasColumnName("coins");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirebaseUid")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("firebase_uid");

                    b.Property<int>("HighScore")
                        .HasColumnType("integer")
                        .HasColumnName("high_score");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean")
                        .HasColumnName("is_anonymous");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_date");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("status_message");

                    b.Property<int>("TotalGamesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("total_games_played");

                    b.Property<long>("TotalScore")
                        .HasColumnType("bigint")
                        .HasColumnName("total_score");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("i_x_users_email");

                    b.HasIndex("FirebaseUid")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_firebase_uid")
                        .HasFilter("firebase_uid IS NOT NULL");

                    b.HasIndex("HighScore")
                        .IsDescending()
                        .HasDatabaseName("i_x_users_high_score");

                    b.HasIndex("LastSeen")
                        .HasDatabaseName("i_x_users_last_seen");

                    b.HasIndex("Level")
                        .HasDatabaseName("i_x_users_level");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_users_status");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_username")
                        .HasFilter("username IS NOT NULL");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid")
                        .HasColumnName("achievement_id");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentProgress")
                        .HasColumnType("integer")
                        .HasColumnName("current_progress");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unlocked");

                    b.Property<bool>("RewardClaimed")
                        .HasColumnType("boolean")
                        .HasColumnName("reward_claimed");

                    b.Property<DateTime?>("UnlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId")
                        .HasDatabaseName("i_x_user_achievements_achievement_id");

                    b.HasIndex("IsUnlocked")
                        .HasDatabaseName("i_x_user_achievements_is_unlocked");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_user_achievements_user_id");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique()
                        .HasDatabaseName("i_x_user_achievements_user_id_achievement_id");

                    b.ToTable("user_achievements");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.UserBattlePassProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<int>>("ClaimedFreeRewards")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("claimed_free_rewards");

                    b.PrimitiveCollection<List<int>>("ClaimedPremiumRewards")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("claimed_premium_rewards");

                    b.PrimitiveCollection<string>("ClaimedRewards")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("claimed_rewards");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("integer")
                        .HasColumnName("current_level");

                    b.Property<int>("CurrentXp")
                        .HasColumnType("integer")
                        .HasColumnName("current_xp");

                    b.Property<bool>("HasPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("has_premium");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<int>("TotalXpEarned")
                        .HasColumnType("integer")
                        .HasColumnName("total_xp_earned");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("HasPremium")
                        .HasDatabaseName("i_x_user_battle_pass_progresses_has_premium");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("i_x_user_battle_pass_progresses_season_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_user_battle_pass_progresses_user_id");

                    b.HasIndex("UserId", "SeasonId")
                        .IsUnique()
                        .HasDatabaseName("i_x_user_battle_pass_progresses_user_id_season_id");

                    b.ToTable("user_battle_pass_progresses");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.UserDailyChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid")
                        .HasColumnName("challenge_id");

                    b.Property<bool>("ClaimedReward")
                        .HasColumnType("boolean")
                        .HasColumnName("claimed_reward");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentProgress")
                        .HasColumnType("integer")
                        .HasColumnName("current_progress");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId")
                        .HasDatabaseName("i_x_user_daily_challenges_challenge_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_user_daily_challenges_user_id");

                    b.HasIndex("UserId", "ChallengeId")
                        .IsUnique()
                        .HasDatabaseName("i_x_user_daily_challenges_user_id_challenge_id");

                    b.HasIndex("UserId", "IsCompleted", "ClaimedReward")
                        .HasDatabaseName("i_x_user_daily_challenges_user_id_is_completed_claimed_reward");

                    b.ToTable("user_daily_challenges");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.UserPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("MusicEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("music_enabled");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("notifications_enabled");

                    b.Property<Dictionary<string, object>>("SettingsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("settings_json");

                    b.Property<bool>("SoundEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("sound_enabled");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("theme");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("VibrationEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("vibration_enabled");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_user_preferences_user_id");

                    b.ToTable("user_preferences");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.UserPremiumContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("BattlePassActive")
                        .HasColumnType("boolean")
                        .HasColumnName("battle_pass_active");

                    b.Property<DateTime?>("BattlePassExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("battle_pass_expires_at");

                    b.Property<int>("BattlePassTier")
                        .HasColumnType("integer")
                        .HasColumnName("battle_pass_tier");

                    b.PrimitiveCollection<string>("OwnedCosmetics")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("owned_cosmetics");

                    b.PrimitiveCollection<string>("OwnedPowerups")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("owned_powerups");

                    b.PrimitiveCollection<string>("OwnedThemes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("owned_themes");

                    b.Property<string>("PremiumTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("premium_tier");

                    b.Property<bool>("SubscriptionActive")
                        .HasColumnType("boolean")
                        .HasColumnName("subscription_active");

                    b.Property<DateTime?>("SubscriptionExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_expires_at");

                    b.Property<Dictionary<string, int>>("TournamentEntries")
                        .HasColumnType("jsonb")
                        .HasColumnName("tournament_entries");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionActive")
                        .HasDatabaseName("i_x_user_premium_contents_subscription_active");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_user_premium_contents_user_id");

                    b.ToTable("user_premium_contents");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.DailyLoginBonus", b =>
                {
                    b.HasOne("SnakeClassic.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("SnakeClassic.Domain.Entities.DailyLoginBonus", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_daily_login_bonuses__users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.FcmToken", b =>
                {
                    b.HasOne("SnakeClassic.Domain.Entities.User", "User")
                        .WithMany("FcmTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_fcm_tokens__users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.Friendship", b =>
                {
                    b.HasOne("SnakeClassic.Domain.Entities.User", "Friend")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_friendships__users_friend_id");

                    b.HasOne("SnakeClassic.Domain.Entities.User", "User")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_friendships__users_user_id");

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.GameReplay", b =>
                {
                    b.HasOne("SnakeClassic.Domain.Entities.Score", "Score")
                        .WithOne("Replay")
                        .HasForeignKey("SnakeClassic.Domain.Entities.GameReplay", "ScoreId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_game_replays__scores_score_id");

                    b.HasOne("SnakeClassic.Domain.Entities.User", "User")
                        .WithMany("GameReplays")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_game_replays__users_user_id");

                    b.Navigation("Score");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.MatchmakingQueue", b =>
                {
                    b.HasOne("SnakeClassic.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_matchmaking_queues__users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.MultiplayerPlayer", b =>
                {
                    b.HasOne("SnakeClassic.Domain.Entities.MultiplayerGame", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_multiplayer_players_multiplayer_games_game_id");

                    b.HasOne("SnakeClassic.Domain.Entities.User", "User")
                        .WithMany("MultiplayerGames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_multiplayer_players__users_user_id");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.Purchase", b =>
                {
                    b.HasOne("SnakeClassic.Domain.Entities.User", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_purchases__users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.Score", b =>
                {
                    b.HasOne("SnakeClassic.Domain.Entities.User", "User")
                        .WithMany("Scores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_scores__users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.TournamentEntry", b =>
                {
                    b.HasOne("SnakeClassic.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Entries")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_tournament_entries_tournaments_tournament_id");

                    b.HasOne("SnakeClassic.Domain.Entities.User", "User")
                        .WithMany("TournamentEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_tournament_entries__users_user_id");

                    b.Navigation("Tournament");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.UserAchievement", b =>
                {
                    b.HasOne("SnakeClassic.Domain.Entities.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_achievements_achievements_achievement_id");

                    b.HasOne("SnakeClassic.Domain.Entities.User", "User")
                        .WithMany("Achievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_achievements_users_user_id");

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.UserBattlePassProgress", b =>
                {
                    b.HasOne("SnakeClassic.Domain.Entities.BattlePassSeason", "Season")
                        .WithMany("UserProgress")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_battle_pass_progresses_battle_pass_seasons_season_id");

                    b.HasOne("SnakeClassic.Domain.Entities.User", "User")
                        .WithMany("BattlePassProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_battle_pass_progresses_users_user_id");

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.UserDailyChallenge", b =>
                {
                    b.HasOne("SnakeClassic.Domain.Entities.DailyChallenge", "Challenge")
                        .WithMany("UserChallenges")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_daily_challenges_daily_challenges_challenge_id");

                    b.HasOne("SnakeClassic.Domain.Entities.User", "User")
                        .WithMany("DailyChallenges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_daily_challenges_users_user_id");

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.UserPreferences", b =>
                {
                    b.HasOne("SnakeClassic.Domain.Entities.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("SnakeClassic.Domain.Entities.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_preferences_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.UserPremiumContent", b =>
                {
                    b.HasOne("SnakeClassic.Domain.Entities.User", "User")
                        .WithOne("PremiumContent")
                        .HasForeignKey("SnakeClassic.Domain.Entities.UserPremiumContent", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_premium_contents_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.BattlePassSeason", b =>
                {
                    b.Navigation("UserProgress");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.DailyChallenge", b =>
                {
                    b.Navigation("UserChallenges");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.MultiplayerGame", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.Score", b =>
                {
                    b.Navigation("Replay");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("SnakeClassic.Domain.Entities.User", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("BattlePassProgress");

                    b.Navigation("DailyChallenges");

                    b.Navigation("FcmTokens");

                    b.Navigation("GameReplays");

                    b.Navigation("MultiplayerGames");

                    b.Navigation("Preferences");

                    b.Navigation("PremiumContent");

                    b.Navigation("Purchases");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("Scores");

                    b.Navigation("SentFriendRequests");

                    b.Navigation("TournamentEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
